version: "3"
services:
  mysql-standalone:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=radhouan
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
  timesheet:
    image: raddane90/timesheet:14
    ports:
      - 8055:8055
    restart: unless-stopped
    depends_on:
      - mysql-standalone